2019-10-17 10:17:02,117 INFO: Microblog startup [in C:\cygwin64\home\tf05079\microblog\app\__init__.py:56]
2019-10-17 11:18:19,456 INFO: Microblog startup [in c:\cygwin64\home\tf05079\microblog\app\__init__.py:56]
2019-10-17 11:52:13,361 INFO: Microblog startup [in c:\cygwin64\home\tf05079\microblog\app\__init__.py:56]
2019-10-17 11:57:08,364 INFO: Microblog startup [in c:\cygwin64\home\tf05079\microblog\app\__init__.py:56]
2019-10-17 12:01:17,828 INFO: Microblog startup [in c:\cygwin64\home\tf05079\microblog\app\__init__.py:56]
2019-10-17 12:03:01,140 INFO: Microblog startup [in c:\cygwin64\home\tf05079\microblog\app\__init__.py:56]
2019-10-17 12:04:34,649 INFO: Microblog startup [in c:\cygwin64\home\tf05079\microblog\app\__init__.py:56]
2019-10-17 12:04:57,226 INFO: Microblog startup [in c:\cygwin64\home\tf05079\microblog\app\__init__.py:56]
2019-10-17 12:07:10,314 INFO: Microblog startup [in c:\cygwin64\home\tf05079\microblog\app\__init__.py:56]
2019-10-17 17:40:08,282 INFO: Microblog startup [in c:\cygwin64\home\tf05079\microblog\app\__init__.py:56]
2019-10-17 17:40:54,554 INFO: Microblog startup [in c:\cygwin64\home\tf05079\microblog\app\__init__.py:56]
2019-10-17 18:04:56,304 INFO: Microblog startup [in c:\cygwin64\home\tf05079\microblog\app\__init__.py:56]
2019-10-17 18:08:02,301 INFO: Microblog startup [in c:\cygwin64\home\tf05079\microblog\app\__init__.py:56]
2019-10-17 18:09:24,361 INFO: Microblog startup [in c:\cygwin64\home\tf05079\microblog\app\__init__.py:56]
2019-10-17 18:10:05,094 INFO: Microblog startup [in c:\cygwin64\home\tf05079\microblog\app\__init__.py:56]
2019-10-17 18:10:40,687 INFO: Microblog startup [in c:\cygwin64\home\tf05079\microblog\app\__init__.py:56]
2019-10-17 18:12:11,217 INFO: Microblog startup [in c:\cygwin64\home\tf05079\microblog\app\__init__.py:56]
2019-10-17 18:14:04,112 INFO: Microblog startup [in c:\cygwin64\home\tf05079\microblog\app\__init__.py:56]
2019-10-17 18:15:49,602 INFO: Microblog startup [in c:\cygwin64\home\tf05079\microblog\app\__init__.py:56]
2019-10-21 10:19:37,631 INFO: Microblog startup [in C:\cygwin64\home\tf05079\microblog\app\__init__.py:56]
2019-10-21 11:23:19,666 INFO: Microblog startup [in c:\cygwin64\home\tf05079\microblog\app\__init__.py:56]
2019-10-21 11:39:40,724 INFO: Microblog startup [in c:\cygwin64\home\tf05079\microblog\app\__init__.py:56]
2019-10-21 11:40:29,510 INFO: Microblog startup [in c:\cygwin64\home\tf05079\microblog\app\__init__.py:56]
2019-10-21 11:47:32,577 INFO: Microblog startup [in c:\cygwin64\home\tf05079\microblog\app\__init__.py:56]
2019-10-21 11:51:21,012 INFO: Microblog startup [in c:\cygwin64\home\tf05079\microblog\app\__init__.py:56]
2019-10-21 11:54:04,296 INFO: Microblog startup [in c:\cygwin64\home\tf05079\microblog\app\__init__.py:56]
2019-10-21 11:54:50,103 INFO: Microblog startup [in c:\cygwin64\home\tf05079\microblog\app\__init__.py:56]
2019-10-21 11:09:51,839 INFO: Microblog startup [in C:\cygwin64\home\tf05079\microblog\app\__init__.py:56]
2019-10-21 11:20:26,880 INFO: Microblog startup [in C:\cygwin64\home\tf05079\microblog\app\__init__.py:56]
2019-10-21 11:20:39,087 ERROR: Exception on /user/TF05079 [GET] [in c:\cygwin64\home\tf05079\microblog\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\cygwin64\home\tf05079\microblog\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\cygwin64\home\tf05079\microblog\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\cygwin64\home\tf05079\microblog\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\cygwin64\home\tf05079\microblog\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\cygwin64\home\tf05079\microblog\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\cygwin64\home\tf05079\microblog\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\cygwin64\home\tf05079\microblog\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\cygwin64\home\tf05079\microblog\app\routes.py", line 68, in user
    return render_template('user.html', user=my_user, posts=posts)
  File "c:\cygwin64\home\tf05079\microblog\venv\lib\site-packages\flask\templating.py", line 140, in render_template
    ctx.app,
  File "c:\cygwin64\home\tf05079\microblog\venv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\cygwin64\home\tf05079\microblog\venv\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "c:\cygwin64\home\tf05079\microblog\venv\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\cygwin64\home\tf05079\microblog\venv\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\cygwin64\home\tf05079\microblog\venv\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\cygwin64\home\tf05079\microblog\app\templates\user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\cygwin64\home\tf05079\microblog\app\templates\base.html", line 30, in top-level template code
    {% block content %}{% endblock %}
  File "C:\cygwin64\home\tf05079\microblog\app\templates\user.html", line 21, in block "content"
    {% include '_post.html' %}
  File "C:\cygwin64\home\tf05079\microblog\app\templates\_post.html", line 3, in top-level template code
    <td><img src="{{ post.author.avatar(36) }}"></td>
jinja2.exceptions.UndefinedError: 'str object' has no attribute 'avatar'
2019-10-21 11:20:52,788 ERROR: Exception on /user/TF05079 [GET] [in c:\cygwin64\home\tf05079\microblog\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\cygwin64\home\tf05079\microblog\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\cygwin64\home\tf05079\microblog\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\cygwin64\home\tf05079\microblog\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\cygwin64\home\tf05079\microblog\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\cygwin64\home\tf05079\microblog\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\cygwin64\home\tf05079\microblog\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\cygwin64\home\tf05079\microblog\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\cygwin64\home\tf05079\microblog\app\routes.py", line 68, in user
    return render_template('user.html', user=my_user, posts=posts)
  File "c:\cygwin64\home\tf05079\microblog\venv\lib\site-packages\flask\templating.py", line 140, in render_template
    ctx.app,
  File "c:\cygwin64\home\tf05079\microblog\venv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\cygwin64\home\tf05079\microblog\venv\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "c:\cygwin64\home\tf05079\microblog\venv\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\cygwin64\home\tf05079\microblog\venv\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\cygwin64\home\tf05079\microblog\venv\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\cygwin64\home\tf05079\microblog\app\templates\user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\cygwin64\home\tf05079\microblog\app\templates\base.html", line 30, in top-level template code
    {% block content %}{% endblock %}
  File "C:\cygwin64\home\tf05079\microblog\app\templates\user.html", line 21, in block "content"
    {% include '_post.html' %}
  File "C:\cygwin64\home\tf05079\microblog\app\templates\_post.html", line 3, in top-level template code
    <td><img src="{{ post.author.avatar(36) }}"></td>
jinja2.exceptions.UndefinedError: 'str object' has no attribute 'avatar'
2019-10-21 11:22:48,846 INFO: Microblog startup [in C:\cygwin64\home\tf05079\microblog\app\__init__.py:56]
